### ISSUE TITLE
test with clusters with large number of images

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#224]
**Describe the solution you'd like**
test with clusters with thousands of images

**Comment by pmengelbert** [comment]
# Test Results

## Versions used

**Eraser**: Eraser was run using a patched version of v0.5.0, using a patched
version of Trivy. This was necessary because there are outstanding changes to
both eraser and trivy which are awaiting review and merge.

Eraser commit: [a904dd27caf44545cc55ef897afb662af6d69c39](https://github.com/pmengelbert/eraser/tree/a904dd27caf44545cc55ef897afb662af6d69c39)

**Trivy**: Patched version found here: [a0c3968b6167b0e040139031bc66cf5b6311dbcc](https://github.com/pmengelbert/trivy/tree/a0c3968b6167b0e040139031bc66cf5b6311dbcc)

**Containerd / CRI**:
```
$ crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.6.4+azure-4
RuntimeApiVersion:  v1alpha2
```

## Setup
The following Dockerfile and script was used to load 1500 images into the
cluster. Alpine 3.7.3 was chosen because it is known to be vulnerable. To
ensure that images weren't completely removed when deleted by ImageID, random
information was added to the images, resulting in unique ImageIDs for each image.

The end result is 1500 vulnerable images on each node.

### Dockerfile
```dockerfile
FROM alpine:3.7.3
COPY random .
```

### Script
```bash
#!/usr/bin/env bash
set -exuo pipefail

export CONTAINERD_NAMESPACE=k8s.io
cd t || exit 1
_n="$1"

for ((i=0;i<"$_n";i++)); do
    head -c 256 </dev/urandom >random
    /root/bin/buildctl b --local context=. --local dockerfile=. --frontend=dockerfile.v0 --output="type=oci,dest=/tmp/local.tar,name=localimage:v${i}"
    ctr i import /tmp/local.tar
done
```

## Was it successful?
Mostly. 

### The good
All images were sent to the scanner. The 1500 vulnerable images were all
discovered to be vulnerable. Those 1500 images were completely removed. The
only images left on the cluster after the fact were, more or less, what the
cluster started with

### The bad
46 images could not be scanned. All 46 that failed were `mcr` images. The error
message was as follows:

```
"failed analysis: analyze error: failed to analyze layer:  : post handler
error: post handler error: failed to search rekor records: failed to search:
&{0 } (*models.Error) is not supported by the TextConsumer, can be resolved by
supporting TextUnmarshaler interface"
```

A more detailed error:
```
"failed analysis:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/scanner/scan.go:127
  - analyze error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.Inspect
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/fanal/artifact/image/image.go:130
  - failed to analyze layer:  :
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect.func1
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/fanal/artifact/image/image.go:237
  - post handler error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/fanal/artifact/image/image.go:326
  - post handler error:
    github.com/aquasecurity/trivy/pkg/fanal/handler.Manager.PostHandle
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/fanal/handler/handler.go:75
  - failed to search rekor records:
    github.com/aquasecurity/trivy/pkg/attestation/sbom.(*Rekor).RetrieveSBOM
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/attestation/sbom/rekor.go:37
  - failed to search:
    github.com/aquasecurity/trivy/pkg/rekor.(*Client).Search
        /go/pkg/mod/github.com/pmengelbert/trivy@v0.0.0-20221114170249-a0c3968b6167/pkg/rekor/client.go:78
  - &{0 } (*models.Error) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface"
```

### What's happening here?

I'm not sure, but here's a guess: Trivy attempts to verify SBOM data using
`rekor`. It can't locate signature info about MCR images.

### What should we do about the failures?

I'm not sure. Should we disable SBOM verification in trivy?

## Measurements

### Time
| Event | Node 1 | Node 2 | Node 3 |
|-------|----------|---------|----------|
| Collector start | 1668785130              | 1668485131            | 1668785131 |
| First image scan | 1668785136 *(6s)*      | 1668785137  *(6s)*    | 1668785137 *(6s)* |
| Last image scan | 1668787928 *(46m)*      | 1668787597  *(41m)*   | 1668787731 *(43m)* |
| First image removal | 1668787931          | 1668787598            | 1668787732 |
| Last image removal | 1668788049 *(2m)*    | 1668787832  *(4m)*    | 1668787907 *(3m)* |

## Miscellaneous thoughts
If we're going for performance improvements, the scanner is the big bottleneck

**Comment by sozercan** [comment]
@pmengelbert great report! is there a flag to disable sbom verification?

**Comment by pmengelbert** [comment]
@sozercan Yes, I believe that can be done.
