### ISSUE TITLE
Make collector pod's status clearer

### ISSUE THREAD

**Issue by jiashun0011** [eraser-dev/eraser#395]
**Describe the solution you'd like**

When the collector pod is running, its status shows like "NotReady" which may confuse clients.

Can you make the pod's status as `Running` even though either scanner or eraser is not ready?

```
$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                            READY   STATUS     RESTARTS      AGE
eraser-system   collector-aks-nodes-11597922-vmss000000-dpkqt   2/3     NotReady   0             19s
eraser-system   eraser-controller-manager-7ddc6c4fdb-z9lzp      1/1     Running    0             21s
```

**Comment by pmengelbert** [comment]
I encountered this as well when testing out eraser. Specifically, it's the `collector` container within the `collector-aks-nodes-11597922-vmss000000-...` pod that registers as `NotReady`.

I think what's happening is that the `collector` pod runs to completion and is therefore unresponsive. In order to keep it `Ready`, we could have it idle until the erasure process is complete.

**Comment by pmengelbert** [comment]
@jiashun0011 @salaxander PR #430 has been opened to address this
