### ISSUE TITLE
track trivy eraser image vulnerabilities as a recurring job

### ISSUE THREAD

**Issue by ashnamehrotra** [eraser-dev/eraser#783]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Track trivy eraser image vulnerabilities more frequently.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by inFocus7** [comment]
Is the definition of done essentially creating a Github workflow cron job to scan the images daily/`x`-ly, kind of like in [test.yaml](https://github.com/inFocus7/eraser/blob/7cdb6eb5a14eece9a2b35a19d0485067e8728318/.github/workflows/test.yaml#L137-L186)?


If the above...
- Do we only want to scan images built from `main`, like we do in `test.yaml`? 
- Do we want to scan latest release(s) as well? 
    - I tried doing `docker pull ghcr.io/eraser-dev/eraser-trivy-scanner:latest` although got `Error response from daemon: manifest unknown`, so may need to find a different way of automatically knowing/detecting latest releases to scan against.
- We could also allow for manual dispatches on a user-defined `version` to scan, but that may be a future feature if it seems needed/worth it.

**Comment by ashnamehrotra** [comment]
@inFocus7 yes thats correct! We only want to scan the eraser images built from main, and we don't have the latest tags, just the tags relevant to each version release. So each time you want to scan the latest version you will have to build it like it in test.yaml.

**Comment by inFocus7** [comment]
@ashnamehrotra Awesome! Could I get assigned this? 
I _may_ have multiple assigned issues, although I've been working on them pre-assigned, just in case lol. I have a possible working branch to scan `main`-built images daily (can change since it's just a cron job), with the ability/possibility of dispatching manually to scan a specific version (although can remove that job if we don't care for it).

**Comment by ashnamehrotra** [comment]
@inFocus7 sounds good, thanks!

**Comment by inFocus7** [comment]
@ashnamehrotra Cool, just pushed up a PR! Not sure if we want to remove the scan from running during [test.yaml](https://github.com/inFocus7/eraser/blob/7cdb6eb5a14eece9a2b35a19d0485067e8728318/.github/workflows/test.yaml#L137-L186) now that we'll have it running in a scheduled manner.

Also not sure if it's possible to test the action pre-merging (possibly not) just to make sure it works as expected, to not have to do possible hot-fixes afterward 🤔

**Comment by ashnamehrotra** [comment]
@inFocus7 thank you! Would it be possible to test it in your fork of Eraser and link it in #858 to make sure it works?

**Comment by inFocus7** [comment]
Just checked, and not sure if I can run it since it's a net-new action and does/has not shown up in the **[Actions](https://github.com/inFocus7/eraser/actions)** page. Would you happen to know if there's a workaround to this?

Maybe I could merge the code into my fork and run it, and if it works, re-put it up for review? 🤔

**Comment by not-fabian** [comment]
Thought of a fun workaround. I created a test account and forked my repo + merged the action to `main`. 

Running [the workflow](https://github.com/not-fabian/eraser/actions/workflows/scan-images.yaml) now, and will update with results from runs! I see some run failures, so good thing we're doing this haha 😅

**Comment by not-fabian** [comment]
@ashnamehrotra (+ @sozercan since they left review comments), is there any reason (if we know) as to why we're manually downloading Trivy binaries in the [test.yaml flow](https://github.com/not-fabian/eraser/blob/7cdb6eb5a14eece9a2b35a19d0485067e8728318/.github/workflows/test.yaml#L155-L162), as opposed to using the [trivy github action](https://github.com/aquasecurity/trivy-action)?

**Comment by not-fabian** [comment]
### Update

So, I ran the tests manually using a dispatch on a [separate fork](https://github.com/not-fabian/eraser/actions/workflows/scan-images.yaml) and they passed. I also pushed the change up to my PR. Both setting a version to test against, and leaving the input blank `` to run against the branch it's running on (main in most cases).

Only thing is: I set it to run scheduled on `25 1 * * *` so 1:25 AM UTC (which should have been a minute ago), although it hasn't ran as scheduled 🤔

**Comment by ashnamehrotra** [comment]
@not-fabian that is a good point! we should be able to use the trivy github action. It looks like the scheduled run ran here? https://github.com/not-fabian/eraser/actions/runs/6104594820/job/16566829244

**Comment by inFocus7** [comment]
@ashnamehrotra Oops i deleted that run to clean up the fork's runs, but yeah I noticed it ran too!
