### ISSUE TITLE
Version is not updated in Makefile

### ISSUE THREAD

**Issue by ashnamehrotra** [eraser-dev/eraser#843]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Version is not updated to latest in Makefile: https://github.com/eraser-dev/eraser/blob/main/Makefile#L1

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by inFocus7** [comment]
Ah, that probably explains why I'm having issues following the setup! 

Was trying to follow [the dev setup guide](https://eraser-dev.github.io/eraser/docs/setup) and tried Helm installations (`helm install eraser charts/eraser`) but hit errors due to pulling a non-existent `v1.1.1` image tag.

Current workaround is just having Helm override to image tag `v1.2.1` (or any [released version/tag](https://github.com/eraser-dev/eraser/pkgs/container/eraser-manager)).

**Comment by sozercan** [comment]
This is due to https://github.com/eraser-dev/eraser/pull/811 not been merged yet (#845 now)

**Comment by ashnamehrotra** [comment]
@sozercan why is it v1.3.0-beta.0 instead of the latest available?

**Comment by sozercan** [comment]
@ashnamehrotra idea is that main branch tracks dev/vNext, while release branches track for each release

**Comment by sozercan** [comment]
Closing with #845
